# Generated by Django 6.0.6 on 2026-06-29 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('task_date', models.DateField(default=django.utils.timezone.now)),
                ('task_type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('pickup_delivery', 'Pickup & Delivery'), ('other', 'Other')], default='delivery', max_length=30)),
                ('num_tasks', models.PositiveIntegerField(default=1)),
                ('time_taken', models.PositiveIntegerField(default=10)),
                ('distance_km', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_number', models.CharField(blank=True, max_length=15)),
                ('pickup_address', models.TextField(blank=True)),
                ('drop_address', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancelled_by', models.CharField(blank=True, choices=[('rider', 'Rider'), ('customer', 'Customer'), ('company', 'Company')], max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='riders.rider')),
            ],
            options={
                'ordering': ['-task_date', '-created_at'],
            },
        ),
    ]
