# Generated by Django 6.0.6 on 2026-07-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=15, unique=True)),
                ('available_tasks', models.PositiveIntegerField(default=0)),
                ('available_minutes', models.PositiveIntegerField(default=0)),
                ('available_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_recharged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_type', models.CharField(choices=[('base', 'Base Plan Rs.49'), ('topup_task', 'Task Top-up Rs.25/task'), ('topup_time', 'Time Top-up Rs.1/min'), ('topup_km', 'Distance Top-up Rs.10/km')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasks_added', models.PositiveIntegerField(default=0)),
                ('minutes_added', models.PositiveIntegerField(default=0)),
                ('km_added', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='tasks.customerwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='customer_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.customerwallet'),
        ),
    ]
