# Generated by Django 6.0.6 on 2026-07-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_customerwallet_customerrecharge_task_customer_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='customer_beta_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='task_work_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
