# Generated by Django 6.0.6 on 2026-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_customer_beta_id_task_task_work_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrecharge',
            name='recharge_type',
            field=models.CharField(choices=[('base', 'Base Plan Rs.49'), ('topup_task', 'Task Top-up Rs.25/task'), ('topup_time', 'Time Top-up Rs.1/min'), ('topup_km', 'Distance Top-up Rs.10/km'), ('custom', 'Custom Recharge')], default='base', max_length=20),
        ),
    ]
