# Generated by Django 6.0.6 on 2026-07-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_customerrecharge_recharge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwallet',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerrecharge',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerrecharge',
            name='minutes_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerrecharge',
            name='recharge_type',
            field=models.CharField(choices=[('manual', 'Manual Recharge'), ('base', 'Base Plan Rs.49'), ('topup_task', 'Task Top-up'), ('topup_time', 'Time Top-up'), ('topup_km', 'KM Top-up'), ('custom', 'Custom Recharge')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerrecharge',
            name='tasks_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerwallet',
            name='available_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerwallet',
            name='available_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
