# Generated by Django 6.0.6 on 2026-06-29 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(default='Bhopal', max_length=100)),
                ('vehicle_type', models.CharField(default='Bike', max_length=50)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'New'), ('training_pending', 'Training Pending'), ('documents_pending', 'Documents Pending'), ('ready', 'Ready for Activation'), ('active', 'Active'), ('inactive', 'Inactive')], default='new', max_length=30)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='riders/photos/')),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='docs/aadhaar/')),
                ('aadhaar_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('pan', models.FileField(blank=True, null=True, upload_to='docs/pan/')),
                ('pan_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='docs/dl/')),
                ('dl_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('other_doc', models.FileField(blank=True, null=True, upload_to='docs/other/')),
                ('overall_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='riders.rider')),
            ],
        ),
        migrations.CreateModel(
            name='RiderTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('not_interested', 'Not Interested'), ('not_reachable', 'Phone Not Reachable'), ('docs_missing', 'Documents Missing'), ('failed_verification', 'Failed Verification'), ('other', 'Other')], max_length=50)),
                ('reason_detail', models.TextField(blank=True)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='riders.rider')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='riders.rider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
