# Generated by Django 6.0.6 on 2026-06-30 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderdocument',
            name='aadhaar',
        ),
        migrations.RemoveField(
            model_name='riderdocument',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='riderdocument',
            name='other_doc',
        ),
        migrations.RemoveField(
            model_name='riderdocument',
            name='pan',
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='aadhaar_back',
            field=models.ImageField(blank=True, null=True, upload_to='docs/aadhaar/'),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='aadhaar_front',
            field=models.ImageField(blank=True, null=True, upload_to='docs/aadhaar/'),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='dl_back',
            field=models.ImageField(blank=True, null=True, upload_to='docs/dl/'),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='dl_front',
            field=models.ImageField(blank=True, null=True, upload_to='docs/dl/'),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='dl_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='insurance_doc',
            field=models.ImageField(blank=True, null=True, upload_to='docs/insurance/'),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='insurance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='marksheet_doc',
            field=models.ImageField(blank=True, null=True, upload_to='docs/marksheet/'),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='marksheet_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='pan_doc',
            field=models.ImageField(blank=True, null=True, upload_to='docs/pan/'),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='police_verification_doc',
            field=models.ImageField(blank=True, null=True, upload_to='docs/police/'),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='police_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='rc_front',
            field=models.ImageField(blank=True, null=True, upload_to='docs/rc/'),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='rc_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='riderdocument',
            name='rc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('account_number_confirm', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=20)),
                ('passbook_image', models.ImageField(blank=True, null=True, upload_to='docs/passbook/')),
                ('verify_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('mismatch', 'Mismatch')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='riders.rider')),
            ],
        ),
    ]
