# Generated by Django 6.0.6 on 2026-06-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_remove_riderdocument_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='beta_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
