# Generated by Django 6.0.6 on 2026-06-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_rider_beta_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='state',
            field=models.CharField(blank=True, default='Madhya Pradesh', max_length=100),
        ),
    ]
