# Generated by Django 6.0.6 on 2026-06-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_rider_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridertraining',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ridertraining',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ridertraining',
            name='final_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ridertraining',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ridertraining',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ridertraining',
            name='training_done_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
